services:
  api:
    build: .
    container_name: bible-api
    environment:
      BIBLE_DB_HOST: postgres
      BIBLE_DB_PORT: "5432"
      BIBLE_DB_NAME: bible_app
      BIBLE_DB_USER: bible
      BIBLE_DB_PASSWORD: biblepassword
      OLLAMA_URL: http://ollama:11434
      OLLAMA_MODEL: qwen2:7b
      AUTH_PEPPER: c1CMQ0_gBnD6pBIIurIkKE5dTxVuS0YNIAY06DTb18o
      AUTH_CAPTCHA_BYPASS: 8kzG3908GpxBUf-fMBhyQzNJ5OjSJBLi
      REDIS_URL: redis://redis:6379/0
      OPENAI_CITATION_ENABLED: "1"
      OPENAI_KEY_ENCRYPTION_SECRET: change-me
    ports:
      - "9000:9000"
    volumes:
      - ./:/app
      - hf_cache:/app/.cache/huggingface
    depends_on:
      - postgres
      - ollama
      - redis
    command: uvicorn api.main:app --reload --host 0.0.0.0 --port 9000
    restart: unless-stopped
  ollama:
    image: ollama/ollama:latest
    container_name: bible-ollama
    ports:
      - "11434:11434"
    volumes:
      - ollama:/root/.ollama
    restart: unless-stopped
  postgres:
    image: pgvector/pgvector:pg15
    container_name: bible-postgres
    environment:
      POSTGRES_USER: bible
      POSTGRES_PASSWORD: biblepassword
      POSTGRES_DB: bible_app
    ports:
      - "5432:5432"
    volumes:
      - ./pgdata:/var/lib/postgresql/data
      - ./db:/docker-entrypoint-initdb.d
    restart: unless-stopped
  redis:
    image: redis:7-alpine
    container_name: bible-redis
    ports:
      - "6379:6379"
    restart: unless-stopped

volumes:
  pgdata:
  ollama:
  hf_cache:
